"""Build assets/js/paper-refs.js from the paper's compiled bibliography.

The paper (Springer Nature, author-year) cites as "(Lew et al. 2022)" and
lists references alphabetically without numbers. This reads its main.bbl and
writes, for every citation key, the paper's own label and formatted entry, so
the website can cite exactly as the paper does.

    python3 tools/paper_refs.py path/to/main.bbl
"""
import html
import json
import re
import sys
import unicodedata

ACCENTS = {'"': "\u0308", "'": "\u0301", "`": "\u0300", "^": "\u0302",
           "~": "\u0303", "v": "\u030c", "u": "\u0306", "c": "\u0327",
           "=": "\u0304", ".": "\u0307", "H": "\u030b"}
SYMBOLS = {r"\mu": "\u03bc", r"\alpha": "\u03b1", r"\l": "\u0142",
           r"\L": "\u0141", r"\o": "\u00f8", r"\ss": "\u00df", r"\i": "\u0131"}


def detex(s):
    """LaTeX text -> plain Unicode (HTML escaping is done later)."""
    s = re.sub(r"\{\\natexlab\{([^}]*)\}\}|\\natexlab\{([^}]*)\}",
               lambda m: m.group(1) or m.group(2), s)
    s = re.sub(r"\\urlprefix\s*", "", s)
    s = re.sub(r"\\(?:url|doi|eprint)(?:\[[^]]*\])?\{([^}]*)\}", r"\1", s)
    # accents: \"o, \"{o}, {\"o}, \v{s}
    s = re.sub(r"\{?\\([\"'`^~vuc=.H])\s*\{?([A-Za-z]|\\i)\}?\}?",
               lambda m: unicodedata.normalize(
                   "NFC", ("\u0131" if m.group(2) == r"\i" else m.group(2)) + ACCENTS[m.group(1)]), s)
    s = re.sub(r"\$\^\{?([^$}]*)\}?\$", lambda m: {"2": "\u00b2", "3": "\u00b3"}.get(m.group(1), "^" + m.group(1)), s)
    for k, v in SYMBOLS.items():
        s = re.sub(r"\$?" + re.escape(k) + r"(?![A-Za-z])\$?", v, s)
    s = s.replace(r"\&", "&").replace(r"\%", "%").replace(r"\#", "#").replace(r"\_", "_")
    s = s.replace("~", "\u00a0").replace("---", "\u2014").replace("--", "\u2013")
    s = re.sub(r"\\[a-zA-Z]+\s*", "", s)   # any command left (e.g. \emph) keeps its argument
    s = s.replace("{", "").replace("}", "").replace("$", "")
    return re.sub(r"\s+", " ", s).strip()


def main(bbl_path, out_path="assets/js/paper-refs.js"):
    bbl = open(bbl_path, encoding="utf-8").read()
    body = bbl[bbl.index(r"\bibitem"):bbl.rindex(r"\end{thebibliography}")]
    refs = {}
    for order, chunk in enumerate(re.split(r"\\bibitem", body)[1:], 1):
        m = re.match(r"\s*\[(.*?)\]\{([^}]+)\}(.*)", chunk, re.S)
        opt, key, text = m.group(1), m.group(2), m.group(3)
        if opt.startswith("{") and opt.endswith("}"):
            opt = opt[1:-1]
        lab = re.match(r"(.*?)\((.*?)\)", opt, re.S)
        author = detex(lab.group(1))
        year = detex(lab.group(2))
        text = detex(text)
        url = re.search(r"(https?://\S+?)(?:,|\s|$)", text)
        refs[key] = {"order": order, "author": author, "year": year,
                     "html": html.escape(text), "url": url.group(1).rstrip(".") if url else None}
    js = ("/* Generated by tools/paper_refs.py from the paper's main.bbl: the paper's\n"
          "   own author-year labels and reference entries, in the paper's order. */\n"
          "window.PAPER_REFS = " + json.dumps(refs, ensure_ascii=False, indent=0) + ";\n")
    open(out_path, "w", encoding="utf-8").write(js)
    print(len(refs), "references ->", out_path)


if __name__ == "__main__":
    main(*sys.argv[1:])
